/**
 * @author Chad Koslovsky <chad@technomnancy.it>
 * @file Description
 * @desc Created on 2021-06-26 10:46:56 pm
 * @copyright TechnomancyIT
 */
import { BrowserWindow, screen, ipcMain } from 'electron';
import path from 'path';
import { render } from 'react-dom';
import React, { FC, useState } from 'react';
import wallpaper from 'electron-wallpaper-napi';
import globalKeys from 'iohook';

//Configuration is auto generated by YML script inside craco.config.js

interface WallpaperProps {}

export default () => {
  let mainWindow: null | BrowserWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegrationInSubFrames: true,
      webviewTag: true,
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      webSecurity: false,
    },
    // fullscreen: true,
    type: 'desktop',
    transparent: true,
    frame: false,
  });

  //mainWindow.webContents.openDevTools();

  // let dummyWindow: null | BrowserWindow = new BrowserWindow({
  //   webPreferences: {
  //     nodeIntegrationInSubFrames: true,
  //     webviewTag: true,
  //     nodeIntegration: true,
  //     enableRemoteModule: true,
  //     contextIsolation: false,
  //     webSecurity: false,
  //   },

  //   type: 'desktop',
  //   fullscreen: true,
  //   transparent: true,
  //   frame: false,
  // });

  const ddir = path.join(__dirname, '../renderer/', 'dummy/');
  const cdir = path.join(__dirname, '../renderer/', 'child/');

  // setTimeout(() => {
  //   dummyWindow?.loadURL(`file://${ddir}index.html`);
  // }, 2000);

  // console.log('eek', ddir);

  // dummyWindow.show();
  // dummyWindow.moveTop();
  // dummyWindow.setMinimizable(false);
  // dummyWindow.setClosable(false);
  // dummyWindow.setFocusable(true);
  // dummyWindow.setResizable(false);
  // dummyWindow.setVisibleOnAllWorkspaces(true);

  // dummyWindow.setKiosk;

  // dummyWindow.setIgnoreMouseEvents(true);

  // dummyWindow.setAlwaysOnTop(true);

  // dummyWindow.on('focus', () => {
  //   dummyWindow?.moveTop();
  // });

  setTimeout(() => {
    child?.loadURL(`file://${cdir}index.html`);
  }, 20000);

  let child = new BrowserWindow({
    type: 'desktop',
    transparent: true,
    frame: false,
    fullscreen: true,
    webPreferences: {
      nodeIntegrationInSubFrames: true,
      webviewTag: true,
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      webSecurity: false,
    },
  });

  child.show();

  child.setIgnoreMouseEvents(true, { forward: true });

  //child.webContents.openDevTools();

  ipcMain.on('wpClick', (e, css) => {
    // console.log(mouse());
  });

  // dummyWindow.webContents.openDevTools();

  const dir = path.join(__dirname, '../renderer/', 'wallpaper/');

  mainWindow.setKiosk(true);

  // mainWindow.webContents.openDevTools();

  mainWindow.webContents.on('did-navigate', () => {
    setTimeout(() => {
      console.log('RAN?');
      wallpaper.attachWindow(mainWindow);
    }, 100);
  });

  globalKeys.on('mouseclick', (event: any) => {
    console.log('ran', screen.getCursorScreenPoint(), event);

    if (event.button === 1)
      mainWindow?.webContents.send('some-name', screen.getCursorScreenPoint());

    /* You get object like this
    {
      type: 'mousemove',
      x: 700,
      y: 400
    }
   */
  });

  //Register and start hook
  globalKeys.start();

  // setTimeout(() => {
  //   wallpaper.attachWindow(mainWindow);
  // }, 5000);
  //wallpaper.attachWindow(mainWindow);

  setTimeout(() => {
    mainWindow?.loadURL(`file://${dir}index.html`);
  }, 20000);

  //mainWindow.webContents.openDevTools();

  //mainWindow.setIgnoreMouseEvents(true);

  // function terd() {
  //   console.log(screen.getCursorScreenPoint());
  //   mainWindow?.webContents.send('some-name', screen.getCursorScreenPoint());
  //   setTimeout(() => {
  //     terd();
  //   }, 1000);
  // }

  // terd();
};
