/**
 * @author Chad Koslovsky <chad@technomnancy.it>
 * @file Description
 * @desc Created on 2021-06-26 10:46:56 pm
 * @copyright TechnomancyIT
 */
import { BrowserWindow, screen, ipcMain } from 'electron';
import path from 'path';
import wallpaper from 'electron-wallpaper-napi';
import globalKeys from 'iohook';

//Configuration is auto generated by YML script inside craco.config.js

interface WallpaperProps {}

export default () => {
  let mainWindow: null | BrowserWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegrationInSubFrames: true,
      webviewTag: true,
      nodeIntegration: true,
      enableRemoteModule: true,
      contextIsolation: false,
      webSecurity: false,
    },
    // fullscreen: true,
    type: 'desktop',
    transparent: false,
    frame: false,
  });

  const cdir = path.join(__dirname, '../renderer/', 'child/');

  // setTimeout(() => {
  //   child?.loadURL(`file://${cdir}index.html`);
  // }, 20000);

  // let child = new BrowserWindow({
  //   type: 'desktop',
  //   transparent: true,
  //   frame: false,
  //   fullscreen: true,
  //   webPreferences: {
  //     nodeIntegrationInSubFrames: true,
  //     webviewTag: true,
  //     nodeIntegration: true,
  //     enableRemoteModule: true,
  //     contextIsolation: false,
  //     webSecurity: false,
  //   },
  // });

  // child.show();

  mainWindow.setIgnoreMouseEvents(true);

  // mainWindow.webContents.openDevTools();

  ipcMain.on('wpClick', (e, css) => {
    // console.log(mouse());
  });

  const dir = path.join(__dirname, '../renderer/', 'wallpaper/');

  mainWindow.setKiosk(true);

  // mainWindow.webContents.openDevTools();

  mainWindow.webContents.on('did-navigate', () => {
    setTimeout(() => {
      wallpaper.attachWindow(mainWindow);
    }, 100);
  });

  mainWindow?.loadURL(`file://${dir}index.html`);

  globalKeys.on('mouseup', (event: any) => {
    if (event.button === 1)
      mainWindow?.webContents.send('some-name', screen.getCursorScreenPoint());

    /* You get object like this
    {
      type: 'mousemove',
      x: 700,
      y: 400
    }
   */
  });

  //Register and start hook
  globalKeys.start(false);

  // setTimeout(() => {
  //   wallpaper.attachWindow(mainWindow);
  // }, 5000);
  //wallpaper.attachWindow(mainWindow);
  // mainWindow?.loadURL(`file://${dir}index.html`);
};
